version: '3.7'

services: 
    db:
        image: mariadb
        environment: 
            MYSQL_ROOT_PASSWORD: 'example'
            MYSQL_DATABASE: djangoProject
        

    web:
        build: .
        command:
            - /bin/bash
            - -c
            - |
              sleep 10
              python3 manage.py makemigrations
              python3 manage.py migrate
              python3 manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
        depends_on: 
            - db
